name: Hey Be See
favicon: null
layout_spectrum: 0.2611645
typography_spectrum: 0.373689
title: Hey Be See - Got Nothing to Lose
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.3546051
  lightness: 0.8815107
  saturation: 0.9238202
  rhythmicContrast: 0.4900841
purpose: []
